"""address_field_updation

Revision ID: 680c42d1bd65
Revises: 00b53cc21eba
Create Date: 2024-08-18 10:29:49.169252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680c42d1bd65'
down_revision: Union[str, None] = '00b53cc21eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('residing_address', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_residing_address'), 'users', ['residing_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_residing_address'), table_name='users')
    op.drop_column('users', 'residing_address')
    # ### end Alembic commands ###
